# Generated by Django 5.2.13 on 2026-04-30 19:04

import apps.game.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('xp_required', models.IntegerField()),
                ('bonus_coins', models.DecimalField(decimal_places=2, max_digits=12)),
                ('free_spins', models.IntegerField(default=0)),
                ('prize_name', models.CharField(max_length=100)),
                ('prize_icon', models.CharField(max_length=100)),
                ('prize_rarity', models.CharField(default='comum', max_length=20)),
                ('house_edge_modifier', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='JackpotPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, default=500, max_digits=12)),
                ('contribution_rate', models.FloatField(default=0.02)),
                ('min_amount', models.DecimalField(decimal_places=2, default=500, max_digits=12)),
                ('last_won_at', models.DateTimeField(blank=True, null=True)),
                ('last_won_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FreeSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('is_used', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('level_up', 'Level Up'), ('scatter', 'Scatter Bonus'), ('promo', 'Promotion'), ('admin', 'Admin Grant')], default='level_up', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.game.models._default_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_spin_records', to='users.userprofile')),
            ],
            options={
                'ordering': ['granted_at'],
                'indexes': [models.Index(fields=['user', 'is_used', 'expires_at'], name='game_freesp_user_id_41f491_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('result_reels', models.JSONField()),
                ('payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('combination_type', models.CharField(max_length=100)),
                ('xp_earned', models.IntegerField(default=0)),
                ('rtp_at_spin', models.FloatField(default=0.0)),
                ('near_miss', models.BooleanField(default=False)),
                ('is_free_spin', models.BooleanField(default=False)),
                ('jackpot_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wild_used', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='users.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='game_spinhi_timesta_114e11_idx'), models.Index(fields=['user', '-timestamp'], name='game_spinhi_user_id_dd0b7d_idx')],
            },
        ),
    ]
